### /init: "-1" means that value is not used

POST http://{{host}}/init
Content-Type: application/json

{
  "testId": "test",
  "testLengthSeconds": -1,
  "msgsPerProcessInSecond": -1,
  "msgSizeBytes": -1,
  "batchSizeSend": -1,
  "senderConcurrency": 4,
  "batchSizeReceive": -1,
  "receiverConcurrency": 4,
  "mqConfig": {
    "host": "{{mqConfigHost}}",
    "port": "{{mqConfigPort}}",
    "table": "{{mqConfigTable}}",
    "database":"{{mqConfigDatabase}}",
    "username": "{{mqConfigUsername}}",
    "password": "{{mqConfigPassword}}",
    "sslEnabled": "{{sslEnabled}}"
  }
}

### /sender: "-1" means that value is not used

POST http://{{host}}/start/sender
Content-Type: application/json

{
  "testId": "test",
  "testLengthSeconds": 10,
  "msgsPerProcessInSecond": 1000,
  "msgSizeBytes": 100,
  "batchSizeSend": 10,
  "senderConcurrency": 4,
  "batchSizeReceive": -1,
  "receiverConcurrency": 4,
  "mqConfig": {
    "host": "{{mqConfigHost}}",
    "port": "{{mqConfigPort}}",
    "table": "{{mqConfigTable}}",
    "database":"{{mqConfigDatabase}}",
    "username": "{{mqConfigUsername}}",
    "password": "{{mqConfigPassword}}",
    "sslEnabled": "{{sslEnabled}}"
  }
}

### /receiver: "-1" means that value is not used

POST http://{{host}}/start/receiver
Content-Type: application/json

{
  "testId": "test",
  "testLengthSeconds": -1,
  "msgsPerProcessInSecond": -1,
  "msgSizeBytes": -1,
  "batchSizeSend": -1,
  "senderConcurrency": 4,
  "maxSendInFlight": -1,
  "batchSizeReceive": 10,
  "receiverConcurrency": 4,
  "mqConfig": {
    "host": "{{mqConfigHost}}",
    "port": "{{mqConfigPort}}",
    "table": "{{mqConfigTable}}",
    "database":"{{mqConfigDatabase}}",
    "username": "{{mqConfigUsername}}",
    "password": "{{mqConfigPassword}}",
    "sslEnabled": "{{sslEnabled}}"
  }
}

### /cleanup:  "-1" means that value is not used

POST http://{{host}}/cleanup
Content-Type: application/json

{
  "testId": "test",
  "testLengthSeconds": -1,
  "msgsPerProcessInSecond": -1,
  "msgSizeBytes": -1,
  "batchSizeSend": -1,
  "senderConcurrency": 4,
  "maxSendInFlight": -1,
  "batchSizeReceive": -1,
  "receiverConcurrency": 4,
  "mqConfig": {
    "host": "{{mqConfigHost}}",
    "port": "{{mqConfigPort}}",
    "table": "{{mqConfigTable}}",
    "database":"{{mqConfigDatabase}}",
    "username": "{{mqConfigUsername}}",
    "password": "{{mqConfigPassword}}",
    "sslEnabled": "{{sslEnabled}}"
  }
}

### /in-progress

GET http://{{host}}/in-progress

### /metrics

GET http://{{host}}/metrics
