{
 "title": "MQPerf Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "span",
    "label": "Span",
    "query": "1m,2m,3m,4m,5m,6m,7m,8m,9m,10m,12m,14m,15m,16m,18m,20m,25m,30m,35m,40m,45m,50m,55m,1h"
   }
  ]
 },
 "panels": [
  {
   "title": "Receive total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mqperf_received_total" }
   ]
  },
  {
   "title": "Max of total receive rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(mqperf_received_total[$span]))"
    }
   ]
  },
  {
   "title": "Avg of total receive rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(mqperf_received_total[$span]))"
    }
   ]
  },
  {
   "title": "Send total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mqperf_sent_total" }
   ]
  },
  {
   "title": "Max of total sent rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(mqperf_sent_total[$span]))"
    }
   ]
  },
  {
   "title": "Avg of total sent rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(mqperf_sent_total[$span]))"
    }
   ]
  },
  {
   "title": "Receive rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mqperf_received_total[$span])\n\n"
    }
   ]
  },
  {
   "title": "Receive rate over 1m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mqperf_received_total[1m])\n"
    }
   ]
  },
  {
   "title": "95% quantile of 1m receive rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.95, mqperf_received_1m_rate[$span])"
    }
   ]
  },
  {
   "title": "95th percentile of receive latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mqperf_receive_latency_ms_bucket[$span])) by (le, host))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mqperf_receive_latency_ms_bucket[$span])) by (le))"
    }
   ]
  },
  {
   "title": "Median receive latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(mqperf_receive_latency_ms_bucket[$span])) by (le))"
    }
   ]
  },
  {
   "title": "Average receive latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mqperf_receive_latency_ms_sum[$span]) / rate(mqperf_receive_latency_ms_count[$span])"
    }
   ]
  },
  {
   "title": "Max 95p of receive latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mqperf_receive_latency_ms_bucket[$span])) by (le))"
    }
   ]
  },
  {
   "title": "95th percentile of send latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mqperf_send_latency_ms_bucket[$span])) by (le, host))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mqperf_send_latency_ms_bucket[$span])) by (le))"
    }
   ]
  },
  {
   "title": "Median send latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(mqperf_send_latency_ms_bucket[$span])) by (le))"
    }
   ]
  },
  {
   "title": "Average send latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mqperf_send_latency_ms_sum[$span]) / rate(mqperf_send_latency_ms_count[$span])"
    }
   ]
  },
  {
   "title": "Max 95p of send latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mqperf_send_latency_ms_bucket[$span])) by (le))"
    }
   ]
  }
 ]
}