global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - 'prometheus.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mqperf'
    scrape_interval: 1s
    honor_labels: true
    static_configs:
      - targets: ['mqperf:8080']
