apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    name: app
spec:
  containers:
  - name: app
    image: ${APP_IMAGE}
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    run: app
spec:
  ports:
  - port: 8080
  - targetPort: 8080
    protocol: TCP
    