apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    name: app
spec:
  replicas: ${APP_MAX_NODES_NUMBER}
  selector:
    matchLabels: 
      name: app
  template:
    metadata:
      name: app
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: ${APP_IMAGE}
        ports:
        - name: http
          containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-group
                  operator: In
                  values:
                  - apps
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - app
              topologyKey: "kubernetes.io/hostname"
