{
 "title": "MQPerf",
 "panels": [
  {
   "title": "mqperf_send_latency_ms",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(mqperf_send_latency_ms_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "mqperf_receive_latency_ms",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(mqperf_receive_latency_ms_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "mqperf_send_latency_ms",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mqperf_send_latency_ms_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "mqperf_receive_latency_ms",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqperf_receive_latency_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "sent and received total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mqperf_sent_total" },
    { "expr": "mqperf_received_total", "legendFormat": "__auto" }
   ]
  }
 ]
}