version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  mqperf:
    image: softwaremill/mqperf-rabbitmq:latest
    depends_on:
      - rabbitmq
    ports:
      - 8080:8080
    hostname: mqperf
    container_name: mqperf