version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  mqperf:
    image: softwaremill/mqperf-rabbitmq:latest
    depends_on:
      - rabbitmq
    ports:
      - 8080:8080
    hostname: mqperf
    container_name: mqperf

  mqperf2:
    image: softwaremill/mqperf-rabbitmq:latest
    environment:
      - http.port=8081
    depends_on:
      - rabbitmq
    ports:
      - 8081:8081
    hostname: mqperf2
    container_name: mqperf2

  mqperf3:
    image: softwaremill/mqperf-rabbitmq:latest
    environment:
      - http.port=8082
    depends_on:
      - rabbitmq
    ports:
      - 8082:8082
    hostname: mqperf3
    container_name: mqperf3


