#!/bin/sh
':' //; exec "$(command -v nodejs || command -v node)" "$0" "$@"
// ^ https://unix.stackexchange.com/questions/65235/universal-node-js-shebang

// https://stackoverflow.com/questions/12941083/execute-and-get-the-output-of-a-shell-command-in-node-js

const childProcess = require("child_process");

/**
 * @param {string} command A shell command to execute
 * @return {Promise<string>} A promise that resolve to the output of the shell command, or an error
 * @example const output = await execute("ls -alh");
 */
function execute(command) {
  /**
   * @param {Function} resolve A function that resolves the promise
   * @param {Function} reject A function that fails the promise
   * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
   */
  return new Promise(function(resolve, reject) {
    /**
     * @param {Error} error An error triggered during the execution of the childProcess.exec command
     * @param {string|Buffer} standardOutput The result of the shell command execution
     * @param {string|Buffer} standardError The error resulting of the shell command execution
     * @see https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback
     */
    childProcess.exec(command, function(error, standardOutput, standardError) {
      if (error) {
        console.log("Error: " + error);
        reject();

        return;
      }

      if (standardError) {
        console.log("Error: " + standardError);
        reject(standardError);

        return;
      }

      resolve(standardOutput);
    });
  });
}

//

async function main() {
  const output = JSON.parse(await execute("cd ~/projects/mqperf; source scripts/conf_env; cd ansible; ansible-inventory --list 2>/dev/null"));
  function hostsFor(group) {
    const r1 = (output[group] || {hosts: []}).hosts.join(' ');
    console.log(group + ': ' + r1);
  }

  hostsFor("tag_group_Sender");
  hostsFor("tag_group_Receiver");
  hostsFor("tag_group_Prometheus");
  hostsFor("tag_group_Rocketmq");
}

main();