name: "Terraform"

on:
  push:
    branches:
      - "feature/github-actions"

  pull_request:
env: 
  CLUSTER_NAME: kafka88
  TF_VAR_BUCKET_NAME: kafka-bucket-mqperf

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'push' }}
        with:
          ref: ${{ github.ref_name }}
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_wrapper: false
      - name: Test terraform
        run: terraform -version
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: latest
      - name: Test terragrunt
        run: terragrunt -version
      - name: Terraform format
        run: terragrunt run-all fmt -check -recursive -diff --terragrunt-working-dir terraform/live/kafka/aws/ --terragrunt-non-interactive
      - name: Terraform plan
        run: terragrunt run-all plan --terragrunt-working-dir terraform/live/kafka/aws/ --terragrunt-non-interactive
      - name: Terraform apply
        if: ${{ success() }}
        run: terragrunt run-all apply --terragrunt-working-dir terraform/live/kafka/aws/  --terragrunt-non-interactive
      # - name: Terraform destroy 
      #   if: ${{ success() }}
      #   run: terragrunt run-all destroy  --terragrunt-working-dir terraform/live/kafka/aws/ --terragrunt-non-interactive
      - name: Checking provider files
        if: ${{ failure() }}
        working-directory: terraform
        run: cat live/kafka/aws/kafka/.terragrunt-cache/provider.tf
